# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37d109210675620889a221f5155dd7ec7f40681d0c4b28cee3850c435de0b23f99c436cfe670b7db38d138fdc63db5c4aaef736369ab21c3b643c9354dd7701c

test:
  secret_key_base: 4e9b8872a9cf93c6a2e2346d8afd2dbc4b7607f90bec2bcc1e4efbccdf4e95c2d2de3c6ed9b7e309c25dbd99643633ec92fe047d726b2da29165e2afa918cddd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
